// Sofia Primary Schools Database
// Data Year: 2024/25

const schoolsData = [
    {
        id: 1,
        name: "Anglo-American School (AAS)",
        type: "Private",
        language: "English",
        district: "Pancharevo",
        address: "Siyanie Street 1, 1137 Pancharevo",
        tuition: 24000,
        oneTimeFee: "€350 application + €3,000 capital",
        foodFee: "Included",
        transportFee: "€1,800 - €2,200",
        currency: "EUR",
        feeNotes: "Capital fee is one-time for new students. Lunch included.",
        phone: "+359 2 923 8810",
        email: "admissions@aas-sofia.org",
        web: "https://www.aas-sofia.org",
        features: "International IB curriculum. Extensive campus. Very high diversity. 2025/26 Tuition (2026/27 pending).",
        lat: 42.6074,
        lng: 23.4037
    },
    {
        id: 2,
        name: "American English Academy (AEA)",
        type: "Private",
        language: "English",
        district: "Lozenets (Gorna Banya Campus)",
        address: "3 Orsova Poliana St, 1619 Sofia",
        tuition: 11000,
        oneTimeFee: "€1,500 new student fee",
        foodFee: "€950",
        transportFee: "€1,200 - €1,500",
        currency: "EUR",
        feeNotes: "Tuition includes textbooks. Capital fee separate.",
        phone: "+359 89 335 7777",
        email: "admission@aeasofia.com",
        web: "https://aeasofia.com",
        features: "US Curriculum. Green campus. Strong community focus. 2025/26 Tuition (2026/27 pending).",
        lat: 42.6585,
        lng: 23.2384
    },
    {
        id: 3,
        name: "St. George International School",
        type: "Private",
        language: "English",
        district: "Lozenets",
        address: "bul. Nikola Y. Vaptsarov 47, 1407 Sofia",
        tuition: 13000,
        oneTimeFee: "€1,000 registration",
        foodFee: "€1,100",
        transportFee: "€1,400 - €1,800",
        currency: "EUR",
        feeNotes: "Mandatory uniform purchase separately. Discounts for siblings.",
        phone: "+359 2 873 00 23",
        email: "reception@stgeorgeschool.bg",
        web: "https://stgeorgeschool.bg",
        features: "Strong STEM/Sports. Dual curriculum. 2025/26 Tuition (2026/27 pending).",
        lat: 42.6685,
        lng: 23.3245
    },
    {
        id: 4,
        name: "British School of Sofia (BSS)",
        type: "Private",
        language: "English",
        district: "Vitosha",
        address: "ul. Georgi Raychev 21, 1619 Sofia",
        tuition: 12500,
        oneTimeFee: "€850 admission",
        foodFee: "€1,000",
        transportFee: "€1,500",
        currency: "EUR",
        feeNotes: "Apple device fee may apply for older students.",
        phone: "+359 886 510 510",
        email: "office@bssofia.bg",
        web: "https://bssofia.bg",
        features: "British Curriculum. Apple Distinguished School. Innovation focus. 2025/26 Tuition (2026/27 pending).",
        lat: 42.6362,
        lng: 23.3089
    },
    {
        id: 5,
        name: "Izzi Science for Kids",
        type: "Private",
        language: "Bilingual",
        district: "Vitosha",
        address: "ul. Angel Karaliychev 10, 1700 Sofia",
        tuition: 8100,
        oneTimeFee: "€30 admission contest",
        foodFee: "Included",
        transportFee: "Optional (Ask for quote)",
        currency: "EUR",
        feeNotes: "Tuition covers resources, food, accident insurance. Extracurriculars included.",
        phone: "+359 88 569 3415",
        email: "info@izzi.academy",
        web: "https://izzi.academy",
        features: "Science-focused (Cambridge Science). Verified 2026/27 Tuition (Grades 1-3).",
        lat: 42.6521,
        lng: 23.3356
    },
    {
        id: 6,
        name: "Private School Sveta Sofia",
        type: "Private",
        language: "Bulgarian",
        district: "Boyana",
        address: "ul. Moreni 3, 1618 Sofia",
        tuition: 6500,
        oneTimeFee: "€60 admission exam",
        foodFee: "€850",
        transportFee: "€1,100",
        currency: "EUR",
        feeNotes: "Discounts for siblings available.",
        phone: "+359 2 959 03 89",
        email: "info@svetasofia.com",
        web: "http://svetasofia.com",
        features: "Strong academic reputation (Math/Language). Competitive entry.",
        lat: 42.6468,
        lng: 23.2764
    },
    {
        id: 7,
        name: "PCMG (Pitagor)",
        type: "Private",
        language: "Bulgarian",
        district: "Vitosha/Manastirski",
        address: "ul. Ralevitsa 80, 1680 Sofia",
        tuition: 7000,
        oneTimeFee: "€50 exam fee",
        foodFee: "€900",
        transportFee: "€1,300",
        currency: "EUR",
        feeNotes: "Known for math competition preparation.",
        phone: "+359 897 925 805",
        email: "office@pitagor-bg.org",
        web: "https://parvagimnazia.com",
        features: "Math-focused. High success rate in national competitions.",
        lat: 42.6592,
        lng: 23.2821
    },
    {
        id: 8,
        name: "Deutsche Schule Sofia",
        type: "Private",
        language: "German",
        district: "Iztok",
        address: "ul. Frederik Joliot-Curie 25, 1113 Sofia",
        tuition: 6800,
        oneTimeFee: "€1,500 admission",
        foodFee: "Included (Preschool only)",
        transportFee: "N/A (Central)",
        currency: "EUR",
        feeNotes: "Linked to German Embassy. Fees subsidized for German nationals.",
        phone: "+359 2 963 43 73",
        email: "ds-sofia@ds-sofia.bg",
        web: "https://ds-sofia.bg",
        features: "German curriculum. Attached to German Embassy. 2025/26 Tuition (2026/27 pending).",
        lat: 42.6695,
        lng: 23.3524
    },
    {
        id: 9,
        name: "Uwekind",
        type: "Private",
        language: "German",
        district: "Boyana (Knyazhevo)",
        address: "ul. Voyvodina mogila 136, 1619 Sofia",
        tuition: 7500,
        oneTimeFee: "€500 enrollment",
        foodFee: "€950",
        transportFee: "€1,450",
        currency: "EUR",
        feeNotes: "IB Diploma program available later.",
        phone: "+359 884 007 055",
        email: "office@uwekind.bg",
        web: "https://uwekind.bg",
        features: "German/English. IB World School. Creative approach. 2025/26 Tuition (2026/27 pending).",
        lat: 42.6558,
        lng: 23.2452
    },
    {
        id: 10,
        name: "Espa School",
        type: "Private",
        language: "Bilingual",
        district: "Vitosha (Kambanite)",
        address: "ul. Gradina 19, 1137 Sofia",
        tuition: 8000,
        oneTimeFee: "€1,200 entry",
        foodFee: "€1,000",
        transportFee: "€1,600",
        currency: "EUR",
        feeNotes: "Focus on arts and foreign languages.",
        phone: "+359 2 961 55 55",
        email: "office@espa.bg",
        web: "https://espa.bg",
        features: "Extended foreign language learning. Focus on arts and culture. 2025/26 Tuition (2026/27 pending).",
        lat: 42.6225,
        lng: 23.3854
    },
    {
        id: 11,
        name: "107 OU (Khan Krum)",
        type: "Public",
        language: "Bulgarian",
        district: "Lozenets",
        address: "ul. Dimitar Hadzhikotsev 44, 1421 Sofia",
        tuition: 0,
        oneTimeFee: "None",
        foodFee: "€3/day (approx)",
        transportFee: "None",
        currency: "EUR",
        feeNotes: "State funded. Parents pay for lunch and optional activities.",
        phone: "+359 2 866 22 75",
        email: "info@107ou.bg",
        web: "https://107ou.bg",
        features: "Top-rated public school. Known for high academic standards.",
        lat: 42.6738,
        lng: 23.3175
    },
    {
        id: 12,
        name: "120 OU (G.S. Rakovski)",
        type: "Public",
        language: "Bulgarian",
        district: "Lozenets",
        address: "ul. Papa Ioan Pavel II 2, 1164 Sofia",
        tuition: 0,
        oneTimeFee: "None",
        foodFee: "€3/day (approx)",
        transportFee: "None",
        currency: "EUR",
        feeNotes: "State funded.",
        phone: "+359 2 866 12 30",
        email: "mail@120ou.com",
        web: "https://120ou.com",
        features: "Central location. Strong community. Innovative teaching.",
        lat: 42.6782,
        lng: 23.3321
    },
    {
        id: 13,
        name: "Lycée Français Victor Hugo",
        type: "Private",
        language: "French",
        district: "Vitosha (Maxi)",
        address: "ul. Obikolna 28, 1700 Sofia",
        tuition: 6500,
        oneTimeFee: "€800 first registration",
        foodFee: "€900",
        transportFee: "€1,400",
        currency: "EUR",
        feeNotes: "French curriculum. Fees may vary by nationality.",
        phone: "+359 2 963 21 19",
        email: "contact@vhugo.org",
        web: "https://vhugo.org",
        features: "Official French curriculum. Diverse international student body. 2025/26 Tuition (2026/27 pending).",
        lat: 42.6453,
        lng: 23.3385
    },
    {
        id: 14,
        name: "Cosmos International School",
        type: "Private",
        language: "English",
        district: "Sofia Region (Osoitsa)",
        address: "Osoitsa village, Sofia Region (Campus)",
        tuition: 6600,
        oneTimeFee: "€250 registration",
        foodFee: "Included",
        transportFee: "Included",
        currency: "EUR",
        feeNotes: "All-inclusive fee structure.",
        phone: "",
        email: "",
        web: "https://cischool.bg",
        features: "British curriculum. Ages 5-18. Campus outside Sofia city. 2025/26 Tuition (2026/27 pending).",
        lat: 42.7454,
        lng: 23.7541
    },
    {
        id: 15,
        name: "Change the World Schools",
        type: "Private",
        language: "English",
        district: "Mladost 4",
        address: "ul. Arh. Bogdan Tomalevski, Sofia",
        tuition: 8200,
        oneTimeFee: "€500 enrollment",
        foodFee: "€950",
        transportFee: "Optional",
        currency: "EUR",
        feeNotes: "Project-based learning focus.",
        phone: "",
        email: "",
        web: "https://www.ctwschools.com",
        features: "American curriculum. Ages 4-14. Project-based learning. 2025/26 Tuition (2026/27 pending).",
        lat: 42.6274,
        lng: 23.3716
    },
    {
        id: 16,
        name: "Maple Bear Sofia",
        type: "Private",
        language: "English",
        district: "Boyana",
        address: "38 Panoramen Pyt, 1616 Sofia",
        tuition: 7000,
        oneTimeFee: "€400",
        foodFee: "Included",
        transportFee: "€1,200",
        currency: "EUR",
        feeNotes: "Canadian methodology.",
        phone: "",
        email: "",
        web: "https://sofia-school.maplebear.bg/en/",
        features: "Canadian curriculum. Ages 5-10. Elementary focus. 2025/26 Tuition (2026/27 pending).",
        lat: 42.6548,
        lng: 23.2550
    },
    {
        id: 17,
        name: "Discover Montessori School",
        type: "Private",
        language: "Bilingual",
        district: "Lozenets",
        address: "ul. Bolgrad 6, 1421 Sofia",
        tuition: 9000,
        oneTimeFee: "€800 enrollment",
        foodFee: "€950",
        transportFee: "Optional",
        currency: "EUR",
        feeNotes: "Montessori certified.",
        phone: "",
        email: "",
        web: "https://discovermontessori.bg",
        features: "IB World School (PYP/MYP). Montessori method. 2025/26 Tuition (2026/27 pending).",
        pedagogy: "Montessori",
        lat: 42.6650,
        lng: 23.3200
    },
    {
        id: 18,
        name: "BRITANICA Park School",
        type: "Private",
        language: "English",
        district: "Dragalevtsi",
        address: "ul. Momino Venche 27, Dragalevtsi, Sofia",
        tuition: 8500,
        oneTimeFee: "€450 registration",
        foodFee: "€900",
        transportFee: "€1,350",
        currency: "EUR",
        feeNotes: "Park campus environment.",
        phone: "",
        email: "",
        web: "https://britanica.bg",
        features: "British curriculum. Park campus setting. 2025/26 Tuition (2026/27 pending).",
        lat: 42.6303,
        lng: 23.3132
    },
    {
        id: 19,
        name: "Thomas Edison Private School",
        type: "Private",
        language: "Bulgarian",
        district: "Sofia",
        address: "Sofia, Bulgaria",
        tuition: 6000,
        oneTimeFee: "€300",
        foodFee: "€800",
        transportFee: "Optional",
        currency: "EUR",
        feeNotes: "Strong academic focus.",
        phone: "",
        email: "",
        web: "",
        features: "Top NVO Grade 4 performer (2025). Strong academics. Source: Danybon NVO rankings.",
        lat: 42.6900,
        lng: 23.3400
    },
    {
        id: 20,
        name: "Celestin Freinet Private School",
        type: "Private",
        language: "Bulgarian",
        district: "Sofia",
        address: "Sofia, Bulgaria",
        tuition: 5500,
        oneTimeFee: "€300",
        foodFee: "€750",
        transportFee: "Optional",
        currency: "EUR",
        feeNotes: "Alternative pedagogy.",
        phone: "",
        email: "",
        web: "",
        features: "Freinet pedagogy. Top NVO performer. Source: Danybon NVO rankings.",
        lat: 42.6800,
        lng: 23.3500
    },
    {
        id: 21,
        name: "6 OU (Graf Ignatiev)",
        type: "Public",
        language: "Bulgarian",
        district: "Sredets (Center)",
        address: "ul. 6 Septemvri 16, 1000 Sofia",
        tuition: 0,
        oneTimeFee: "None",
        foodFee: "€3/day (approx)",
        transportFee: "None",
        currency: "EUR",
        feeNotes: "State funded.",
        phone: "+359 2 988 17 13",
        email: "shesto_ou@6ou.org",
        web: "https://6ou.bg",
        features: "Historic school (est. 1899). Central location. Strong reputation. Source: Official school website.",
        lat: 42.6930,
        lng: 23.3250
    },
    {
        id: 22,
        name: "125 SU (Boyan Penev)",
        type: "Public",
        language: "Bulgarian",
        district: "Mladost 1",
        address: "ul. Nikola Genadiev, Mladost 1, Sofia",
        tuition: 0,
        oneTimeFee: "None",
        foodFee: "€3/day (approx)",
        transportFee: "None",
        currency: "EUR",
        feeNotes: "State funded. STEM focus.",
        phone: "",
        email: "",
        web: "https://125su.bg",
        features: "Hosts math competitions. Strong STEM reputation. Source: Danybon math competition mentions.",
        lat: 42.6530,
        lng: 23.3785
    },
    {
        id: 23,
        name: "Waldorf School (Prof. Nikolay Raynov)",
        type: "Private",
        language: "Bulgarian",
        district: "Geo Milev",
        address: "ul. Alexander von Humboldt 7, 1113 Sofia",
        tuition: 5750,
        oneTimeFee: "Contact school",
        foodFee: "Included",
        transportFee: "Optional",
        currency: "EUR",
        feeNotes: "Monthly fee ~575 BGN. Licensed by German Waldorf Federation.",
        phone: "+359 894 377 903",
        email: "admission@waldorf.bg",
        web: "https://waldorf.bg/en/",
        features: "Anthroposophic/Waldorf pedagogy. Arts, crafts, eurythmy, gardening. Individual approach. Est. 2011.",
        pedagogy: "Anthroposophic",
        lat: 42.6785,
        lng: 23.3630
    }
];

