// Sofia Primary Schools Database
// Data Year: 2024/25

const schoolsData = [
    {
        id: 1,
        name: "Anglo-American School (AAS)",
        type: "Private",
        language: "English",
        district: "Pancharevo",
        address: "Siyanie Street 1, 1137 Pancharevo",
        tuition: 24000,
        phone: "+359 2 923 8810",
        email: "admissions@aas-sofia.org",
        web: "https://www.aas-sofia.org",
        features: "International IB curriculum. Extensive campus. Very high diversity.",
        lat: 42.6074,
        lng: 23.4037
    },
    {
        id: 2,
        name: "American English Academy (AEA)",
        type: "Private",
        language: "English",
        district: "Lozenets (Gorna Banya Campus)",
        address: "3 Orsova Poliana St, 1619 Sofia",
        tuition: 11000,
        phone: "+359 89 335 7777",
        email: "admission@aeasofia.com",
        web: "https://aeasofia.com",
        features: "US Curriculum. Green campus. Strong community focus.",
        lat: 42.6585,
        lng: 23.2384
    },
    {
        id: 3,
        name: "St. George International School",
        type: "Private",
        language: "English",
        district: "Lozenets",
        address: "bul. Nikola Y. Vaptsarov 47, 1407 Sofia",
        tuition: 13000,
        phone: "+359 2 873 00 23",
        email: "reception@stgeorgeschool.bg",
        web: "https://stgeorgeschool.bg",
        features: "Strong STEM/Sports. Dual curriculum (Bulgarian & British). New building.",
        lat: 42.6685,
        lng: 23.3245
    },
    {
        id: 4,
        name: "British School of Sofia (BSS)",
        type: "Private",
        language: "English",
        district: "Vitosha",
        address: "ul. Georgi Raychev 21, 1619 Sofia",
        tuition: 12500,
        phone: "+359 886 510 510",
        email: "office@bssofia.bg",
        web: "https://bssofia.bg",
        features: "British Curriculum. Apple Distinguished School. Innovation focus.",
        lat: 42.6362,
        lng: 23.3089
    },
    {
        id: 5,
        name: "Izzi Science for Kids",
        type: "Private",
        language: "Bilingual",
        district: "Vitosha",
        address: "ul. Angel Karaliychev 10, 1700 Sofia",
        tuition: 9500,
        phone: "+359 88 569 3415",
        email: "info@izzi.academy",
        web: "https://izzi.academy",
        features: "Science-focused (Cambridge Science). Hands-on experiments daily.",
        lat: 42.6521,
        lng: 23.3356
    },
    {
        id: 6,
        name: "Private School Sveta Sofia",
        type: "Private",
        language: "Bulgarian",
        district: "Boyana",
        address: "ul. Moreni 3, 1618 Sofia",
        tuition: 6500,
        phone: "+359 2 959 03 89",
        email: "info@svetasofia.com",
        web: "http://svetasofia.com",
        features: "Strong academic reputation (Math/Language). Competitive entry.",
        lat: 42.6468,
        lng: 23.2764
    },
    {
        id: 7,
        name: "PCMG (Pitagor)",
        type: "Private",
        language: "Bulgarian",
        district: "Vitosha/Manastirski",
        address: "ul. Ralevitsa 80, 1680 Sofia",
        tuition: 7000,
        phone: "+359 897 925 805",
        email: "office@pitagor-bg.org",
        web: "https://parvagimnazia.com",
        features: "Math-focused. High success rate in national competitions.",
        lat: 42.6592,
        lng: 23.2821
    },
    {
        id: 8,
        name: "Deutsche Schule Sofia",
        type: "Private",
        language: "German",
        district: "Iztok",
        address: "ul. Frederik Joliot-Curie 25, 1113 Sofia",
        tuition: 6800,
        phone: "+359 2 963 43 73",
        email: "ds-sofia@ds-sofia.bg",
        web: "https://ds-sofia.bg",
        features: "German curriculum. Attached to German Embassy.",
        lat: 42.6695,
        lng: 23.3524
    },
    {
        id: 9,
        name: "Uwekind",
        type: "Private",
        language: "German",
        district: "Boyana (Knyazhevo)",
        address: "ul. Voyvodina mogila 136, 1619 Sofia",
        tuition: 7500,
        phone: "+359 884 007 055",
        email: "office@uwekind.bg",
        web: "https://uwekind.bg",
        features: "German/English. IB World School. Creative approach.",
        lat: 42.6558,
        lng: 23.2452
    },
    {
        id: 10,
        name: "Espa School",
        type: "Private",
        language: "Bilingual",
        district: "Vitosha (Kambanite)",
        address: "ul. Gradina 19, 1137 Sofia",
        tuition: 8000,
        phone: "+359 2 961 55 55",
        email: "office@espa.bg",
        web: "https://espa.bg",
        features: "Extended foreign language learning. Focus on arts and culture.",
        lat: 42.6225,
        lng: 23.3854
    },
    {
        id: 11,
        name: "107 OU (Khan Krum)",
        type: "Public",
        language: "Bulgarian",
        district: "Lozenets",
        address: "ul. Dimitar Hadzhikotsev 44, 1421 Sofia",
        tuition: 0,
        phone: "+359 2 866 22 75",
        email: "info@107ou.bg",
        web: "https://107ou.bg",
        features: "Top-rated public school. Known for high academic standards.",
        lat: 42.6738,
        lng: 23.3175
    },
    {
        id: 12,
        name: "120 OU (G.S. Rakovski)",
        type: "Public",
        language: "Bulgarian",
        district: "Lozenets",
        address: "ul. Papa Ioan Pavel II 2, 1164 Sofia",
        tuition: 0,
        phone: "+359 2 866 12 30",
        email: "mail@120ou.com",
        web: "https://120ou.com",
        features: "Central location. Strong community. Innovative teaching.",
        lat: 42.6782,
        lng: 23.3321
    },
    {
        id: 13,
        name: "Lycée Français Victor Hugo",
        type: "Private",
        language: "French",
        district: "Vitosha (Maxi)",
        address: "ul. Obikolna 28, 1700 Sofia",
        tuition: 6500,
        phone: "+359 2 963 21 19",
        email: "contact@vhugo.org",
        web: "https://vhugo.org",
        features: "Official French curriculum. Diverse international student body.",
        lat: 42.6453,
        lng: 23.3385
    },
    {
        id: 14,
        name: "Cosmos International School",
        type: "Private",
        language: "English",
        district: "Sofia",
        address: "Sofia, Bulgaria",
        tuition: 6600,
        phone: "",
        email: "",
        web: "https://cosmosschool.bg",
        features: "British curriculum. Ages 5-18. Source: International Schools Database.",
        lat: 42.6850,
        lng: 23.3200
    },
    {
        id: 15,
        name: "Change the World Schools",
        type: "Private",
        language: "English",
        district: "Sofia",
        address: "Sofia, Bulgaria",
        tuition: 8200,
        phone: "",
        email: "",
        web: "https://ctws.bg",
        features: "American curriculum. Ages 4-14. Project-based learning. Source: International Schools Database.",
        lat: 42.6750,
        lng: 23.3150
    },
    {
        id: 16,
        name: "Maple Bear Sofia",
        type: "Private",
        language: "English",
        district: "Sofia",
        address: "Sofia, Bulgaria",
        tuition: 7000,
        phone: "",
        email: "",
        web: "https://maplebear.bg",
        features: "Canadian curriculum. Ages 5-10. Elementary focus. Source: International Schools Database.",
        lat: 42.6700,
        lng: 23.3100
    },
    {
        id: 17,
        name: "Discover Montessori School",
        type: "Private",
        language: "Bilingual",
        district: "Lozenets",
        address: "ul. Bolgrad 6, 1421 Sofia",
        tuition: 9000,
        phone: "",
        email: "",
        web: "https://discovermontessori.bg",
        features: "IB World School (PYP/MYP). Montessori method. Ages 1-18. Source: John Catt + International Schools Database.",
        lat: 42.6650,
        lng: 23.3200
    },
    {
        id: 18,
        name: "BRITANICA Park School",
        type: "Private",
        language: "English",
        district: "Dragalevtsi",
        address: "ul. Momino Venche 27, Dragalevtsi, Sofia",
        tuition: 8500,
        phone: "",
        email: "",
        web: "https://britanica.bg",
        features: "British curriculum. Park campus setting. Source: John Catt International School Search.",
        lat: 42.6303,
        lng: 23.3132
    },
    {
        id: 19,
        name: "Thomas Edison Private School",
        type: "Private",
        language: "Bulgarian",
        district: "Sofia",
        address: "Sofia, Bulgaria",
        tuition: 6000,
        phone: "",
        email: "",
        web: "",
        features: "Top NVO Grade 4 performer (2025). Strong academics. Source: Danybon NVO rankings.",
        lat: 42.6900,
        lng: 23.3400
    },
    {
        id: 20,
        name: "Celestin Freinet Private School",
        type: "Private",
        language: "Bulgarian",
        district: "Sofia",
        address: "Sofia, Bulgaria",
        tuition: 5500,
        phone: "",
        email: "",
        web: "",
        features: "Freinet pedagogy. Top NVO performer. Source: Danybon NVO rankings.",
        lat: 42.6800,
        lng: 23.3500
    },
    {
        id: 21,
        name: "6 OU (Graf Ignatiev)",
        type: "Public",
        language: "Bulgarian",
        district: "Sredets (Center)",
        address: "ul. 6 Septemvri 16, 1000 Sofia",
        tuition: 0,
        phone: "+359 2 988 17 13",
        email: "shesto_ou@6ou.org",
        web: "https://6ou.bg",
        features: "Historic school (est. 1899). Central location. Strong reputation. Source: Official school website.",
        lat: 42.6930,
        lng: 23.3250
    },
    {
        id: 22,
        name: "125 SU (Boyan Penev)",
        type: "Public",
        language: "Bulgarian",
        district: "Mladost",
        address: "Mladost District, Sofia",
        tuition: 0,
        phone: "",
        email: "",
        web: "https://125su.bg",
        features: "Hosts math competitions. Strong STEM reputation. Source: Danybon math competition mentions.",
        lat: 42.6475,
        lng: 23.3820
    }
];

